### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 583: illegal multibyte sequence

### ISSUE THREAD

**Issue by LiangzhengChou** [SMTG-Bham/doped#85]
![image](https://github.com/SMTG-Bham/doped/assets/113409054/2a9e4b2e-2bc3-465b-acf3-5b8a17e34c80)
I just installed the doped library and got this error. How can I solve it? from doped.generation import DefectsGenerator works fine.

**Comment by kavanase** [comment]
Hi @LiangzhengChou, this is an odd issue that seems to be caused by the use of an em dash ("–") in one of the yaml files. 
I've now updated to avoid this in the `develop` branch, so this update will be included in the next release of `doped`.
For now, you can install this version of `doped` using: `pip install https://github.com/SMTG-Bham/doped/archive/develop.zip`. Can you please try this and report back?

I see you are running on a Windows system. We have limited support for Windows as this causes a lot of formatting issues within the code, and this is what caused the error here. With this update it should fix this specific issue, but I'm not sure if you will encounter further issues due to the Windows subsystem... If at all possible, we would recommend running on Linux or MacOS

**Comment by LiangzhengChou** [comment]
![image](https://github.com/SMTG-Bham/doped/assets/113409054/8c4c3b7e-df53-4b4a-a9df-e4ec39ad739f)
Thank you very much for your answer. I tried to install doped using pip install https://github.com/SMTG-Bham/doped/archive/develop.zip, but the same problem still occurred. I will follow your advice to install and use doped in Linux environment.

**Comment by kavanase** [comment]
Hmm that's odd, it should definitely have avoided that error at least. Could you try uninstalling `doped` (with `pip uninstall doped`, `conda uninstall doped`) and then installing again with `pip install https://github.com/SMTG-Bham/doped/archive/develop.zip`?
But yes either way, running on Linux or Mac should avoid this issue!

**Comment by LiangzhengChou** [comment]
Oh indeed, your suggestion solved the problem, thank you very much!
